
package apache_cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Dec 15 08:37:33 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "batchId", namespace = "http://apache_cxf/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "batchId", namespace = "http://apache_cxf/")

public class BatchId {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

